#ifndef __cMain__
#define __cMain__

/**
@file
Subclass of cMainFrame, which is generated by wxFormBuilder.
*/

#include "cGUI.h"

//// end generated include

/** Implementing cMainFrame */
class cMain : public cMainFrame
{
	protected:
		// Handlers for cMainFrame events.
		void newMod( wxCommandEvent& event );
		void newSubmod( wxCommandEvent& event );
		void newCategory( wxCommandEvent& event );
		void newFile( wxCommandEvent& event );
		void openProject( wxCommandEvent& event );
		void openOptions( wxCommandEvent& event );
		void Close( wxCommandEvent& event );
	public:
		/** Constructor */
		cMain( wxWindow* parent );
	//// end generated class members

		cNewModDialog* m_newModDialog = nullptr;

};

#endif // __cMain__
