#ifndef __cNewScriptFile__
#define __cNewScriptFile__

/**
@file
Subclass of cNewScriptFileDialog, which is generated by wxFormBuilder.
*/

#include "cGUI.h"

//// end generated include

/** Implementing cNewScriptFileDialog */
class cNewScriptFile : public cNewScriptFileDialog
{
	protected:
		// Handlers for cNewScriptFileDialog events.
		void Close( wxCommandEvent& event );
		void createSQF( wxCommandEvent& event );
	public:
		/** Constructor */
		cNewScriptFile( wxWindow* parent );
	//// end generated class members

};

#endif // __cNewScriptFile__
