#ifndef __cNewHeader__
#define __cNewHeader__

/**
@file
Subclass of cNewHeaderDialog, which is generated by wxFormBuilder.
*/

#include "cGUI.h"

//// end generated include

/** Implementing cNewHeaderDialog */
class cNewHeader : public cNewHeaderDialog
{
	protected:
		// Handlers for cNewHeaderDialog events.
		void Close( wxCommandEvent& event );
		void createHeader( wxCommandEvent& event );
	public:
		/** Constructor */
		cNewHeader( wxWindow* parent );
	//// end generated class members

};

#endif // __cNewHeader__
