#ifndef __cNewCategory__
#define __cNewCategory__

/**
@file
Subclass of cNewCategoryDialog, which is generated by wxFormBuilder.
*/

#include "cGUI.h"

//// end generated include

/** Implementing cNewCategoryDialog */
class cNewCategory : public cNewCategoryDialog
{
	protected:
		// Handlers for cNewCategoryDialog events.
		void Close( wxCommandEvent& event );
		void createCategory( wxCommandEvent& event );
	public:
		/** Constructor */
		cNewCategory( wxWindow* parent );
	//// end generated class members

};

#endif // __cNewCategory__
